language: php

php:
  - 7.1
  - 7.0
  - 5.6

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update
  - travis_retry composer install

script:
  - ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests
